name: Create Release on Semantic Version Tag

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "Build, test and deploy"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "Setting up Artifactory authentication"
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "central", "username": "${env.ARTIFACTORY_USER}", "password": "${env.ARTIFACTORY_TOKEN}"}]'
          githubServer: false

      - name: "Publish to Artifactory"
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: mvn deploy

      - name: "Create release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          java-version: '11'
          distribution: 'adopt'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/java-code-*.jar
