[versions]
fileversioning = "1.3.0"
spotless = "6.20.0"

[libraries]
fileversioning = { module = "gradle.plugin.de.epitschke.gradle:de.epitschke.gradle-file-versioning", version.ref = "fileversioning" }
jib = "com.google.cloud.tools:jib-gradle-plugin:3.3.1"
nebula-contacts-plugin = { module = "com.netflix.nebula.contacts:com.netflix.nebula.contacts.gradle.plugin", version = "7.0.1"}
nebula-mavenscm-plugin = { module = "com.netflix.nebula.maven-scm:com.netflix.nebula.maven-scm.gradle.plugin", version = "20.3.0"}
nebula-publish-plugin = { module = "com.netflix.nebula.maven-publish:com.netflix.nebula.maven-publish.gradle.plugin", version = "20.3.0"}
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version = "1.8.20"}

[plugins]
fileversioning = { id = "de.epitschke.gradle-file-versioning", version.ref = "fileversioning" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
