[versions]
auto-value = "1.9"
jackson = "2.13.1"
javaparser-core = "3.25.4"
javaparser-symbolsolver = "3.15.15"
java-security-toolkit = "1.1.2"
java-security-toolkit-xstream = "1.0.2"
javax-inject = "1"
jtokkit = "0.6.1"
commons-jexl = "3.2.1"
logback = "1.4.5"
maven = "3.8.7"
openai = "0.14.0"
picocli = "4.7.0"
slf4j = "2.0.6"
guice = "5.1.0"
dom4j = "2.1.4"

[libraries]
autovalue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "auto-value" }
codescan-sarif = "io.codescan:sarif-java:1.0"
dom4j = { module = "org.dom4j:dom4j", version.ref = "dom4j" }
commons-jexl = { module= "org.apache.commons:commons-jexl3", version.ref = "commons-jexl"}
commons-lang3 = "org.apache.commons:commons-lang3:3.12.0"
commons-collections4 = "org.apache.commons:commons-collections4:4.4"
contrast-sarif = "com.contrastsecurity:java-sarif:2.0"
gson = "com.google.code.gson:gson:2.9.0"
guice = { module = "com.google.inject:guice", version.ref = "guice" }
immutables = "org.immutables:value:2.9.0"
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
javadiff = "io.github.java-diff-utils:java-diff-utils:4.12"
javaparser-core = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser-core" }
javaparser-symbolsolver-core = { module = "com.github.javaparser:javaparser-symbol-solver-core", version.ref = "javaparser-core" }
javaparser-symbolsolver-model = { module = "com.github.javaparser:javaparser-symbol-solver-model", version.ref = "javaparser-symbolsolver" }
javaparser-symbolsolver-logic = { module = "com.github.javaparser:javaparser-symbol-solver-logic", version.ref = "javaparser-symbolsolver" }
java-security-toolkit = { module = "io.github.pixee:java-security-toolkit", version.ref = "java-security-toolkit" }
java-security-toolkit-xstream = { module = "io.github.pixee:java-security-toolkit-xstream", version.ref = "java-security-toolkit-xstream" }
javax-inject = { module="javax.inject:javax.inject", version.ref = "javax-inject"}
jetbrains-annotations = "org.jetbrains:annotations:23.0.0"
jfiglet = "com.github.lalyos:jfiglet:0.0.8"
jtokkit = { module = "com.knuddels:jtokkit", version.ref="jtokkit" }
juniversalchardet = "com.github.albfernandez:juniversalchardet:2.4.0"
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = "net.logstash.logback:logstash-logback-encoder:7.4"
maven-model = { module = "org.apache.maven:maven-model", version.ref = "maven" }
openai-service = { module = "com.theokanning.openai-gpt3-java:service", version.ref = "openai" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
progressbar = "me.tongfei:progressbar:0.9.3"
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
tuples = "org.javatuples:javatuples:1.2"
kotlinStdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version = "1.7.10" }
jaxen = { module = "jaxen:jaxen", version = "1.2.0" }
xerces-impl = { module = "xerces:xercesImpl", version = "2.12.2" }
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version = "2.9.0" }
java-semver = { module = "com.github.zafarkhaja:java-semver", version = "0.9.0" }
diff-match-patch = { module = "fun.mike:diff-match-patch", version = "0.0.2" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
