name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "Setting up Artifactory authentication"
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "central", "username": "${env.ARTIFACTORY_USER}", "password": "${env.ARTIFACTORY_TOKEN}"}]'
          githubServer: false

      - name: "Build with Maven"
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: mvn --batch-mode --update-snapshots -Pci verify

      - name: "Generate Coverage Badge"
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: "Log coverage percentage"
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: "Commit the JaCoCo badge (if it changed)"
        run: |
          if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Jacoco Coverage Update Action'
          git config --global user.email 'pixee@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
          fi

      - name: "Upload JaCoCo coverage report"
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/